### ISSUE TITLE
Step 7 deployment error:  Set-AzureRmWebApp : Cannot validate argument on parameter 

### ISSUE THREAD

**Issue by JCB2222** [Microsoft/mattercenter#750]
Hi, We are somehow stuck on one of the last steps in step 7.  Due to the fact we are unable to find anything about this error any help is very much appreciated.   

The Dutch line in the error translates (more or less) into:  "The objectlink is not set on a copy of a object"
Appsettings are thereafter not populated on the webapp.

**Set-AzureRmWebApp : Cannot validate argument on parameter 'AppSettings'. De objectverwijzing is niet op een exemplaar van een object
ingesteld.
At C:\beks\mattercenter-master\tree\master\cloud\src\solution\Deployment\Scripts\KeyVault-Config.ps1:192 char:91
+ ... pName -ResourceGroupName $ResourceGroupName -AppSettings $appSettings
+                                                              ~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-AzureRmWebApp], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.SetAzureWebAppCmdlet**

Thx!!!

**Comment by premchandpl** [comment]
@JCB2222 Can you check whether all values are being set in the below code in KeyVault-Config.ps1. If any of the values are empty string, you may get the error that has been shown by you
                        $appSettings = @{ `
				"General:Tenant" = $global:TenantName; `
				"General:SiteURL" = $SiteURL; `
				"General:CentralRepositoryUrl" = $CentralRepositoryUrl; `
				"General:KeyVaultURI" = $kvSettings.VaultUri; `
				"General:KeyVaultClientID" = $ADApplicationId; `
				"General:KeyVaultCertThumbPrint" = $global:thumbPrint;`
				"Search:SearchResultSourceID" = $SearchResultSourceId.ToString();`
				"WEBSITE_LOAD_CERTIFICATES" = $global:thumbPrint;`
			}
In the KeyVault-Config.ps1, write the below line **write-host $appSettings** below the above lines of code save the file and run the powershell script again.

Let me know your findings

**Comment by premchandpl** [comment]
@JCB2222 I executed the scripts in my environment, everything went fine

**Comment by JCB2222** [comment]
Thx for your reply and tips. We manually added all the strings and we were able to start Matter Center but got all kinds of errors during “create new Matter”. 
We scrapped the install and are starting over.

(We will use your suggestion as stated above en keep you posted)

**Comment by JCB2222** [comment]
sorry to tell you , clean install same error (see below).
 Could this possibly be a rights issue somewhere
![step 7 set-azurermweb](https://user-images.githubusercontent.com/29375620/27178183-8e83099a-51c9-11e7-9e9b-1d20e24316c7.png)

**Comment by premchandpl** [comment]
@JCB2222 You can debug the powershell script using "Powershell ISE" and you can debug the posershell script code and let me know if you needs any skype call and we can debug the code.
my skype id is - premchand_76@hotmail.com

**Comment by premchandpl** [comment]
@JCB2222 As discussed in the skype, closing this issue as all the issues are resolved. Let me know if any help is required

**Comment by allenolayiwola** [comment]
Hi @premchandpl,

Tried the suggestions above, still getting the same error. See screenshots before and after trying the above step. Kindly assist.
![capture 1](https://user-images.githubusercontent.com/1235545/27554427-e714bf90-5a9d-11e7-9cec-dd31c8df0caa.PNG)
![capture 2](https://user-images.githubusercontent.com/1235545/27554426-e710d970-5a9d-11e7-9eb9-12e93bcca73b.PNG)

Thanks
