### ISSUE TITLE
Help with remote debugging - Step (3/3) produces error

### ISSUE THREAD

**Issue by shak3800** [Microsoft/mattercenter#95]
Hello everyone!

I'm using Visual Studio 2013 to identify what error is number 2147467261

How can I find out what is this error about ? Where should I add a breakpoint?

I've enabled remote debugging in azure for both sites , I have published the sharepoint web app using the debug instead of release (I've used of course the publishing profile). I ve also attached the debugger to the UI site of matter center. 

None of my breakpoints hits.

Am I doing anything wrong?

**Comment by amitabhm21** [comment]
What browser are you using ? There are known issues with Edge browser in a remote debugging session where the breakpoints don't hit. Can you please try using alternate browser.

**Comment by shak3800** [comment]
@amitabhm21  it works with internet explorer but i'm still trying to figure out how to identify this error on final step. This error appears on last step 3/3 of matter creation.

Where should i add the breakpoint

**Comment by stefvanhooijdonk** [comment]
Look for _LegalDMS in the resource files.
If this is in there somewhere, change it to _MatterCenter.

Stef

**Comment by shak3800** [comment]
@stefvanhooijdonk  I've searched the entire solution , there is nowhere _LegalDms only _MatterCenter.

Error appears in this stage : Step 3/3: Updating metadata of matter library and sharing matter with the users...

I'm still trying to figure out what that error means. If I knew the message of this error I could at least try and fix it but I've searched each post and none had this error before

**Comment by smerentsov** [comment]
Having the same error.
There is this error at errorlogs storage - "String reference not set to an instance of a String. Parameter name: s" Class:MatterProvision, Method: UpdateMetadataForList, Line: 660.

**Comment by shak3800** [comment]
@smerentsov  i'm glad i'm not the only one. Have you made any progress regarding this error?

**Comment by smerentsov** [comment]
@shak3800 No, I can't attach to remote debug due a closed ports by firewall

**Comment by WilsonReddy** [comment]
can you verify below two? also try  unselecting "Include email notification" in third step.
1. In Microsoft.Legal.MatterCenter.SharePointAppWeb->App_GlobalResources file update common_term_set_Groupname value should be MatterCenterTerms

2. In Microsoft.Legal.MatterCenter.ProviderService->App_GlobalResources->Constants.resx, the One_Drive_Content_Type_Group value should be _MatterCenter

**Comment by shak3800** [comment]
@WilsonReddy  yes they are correctly filled by default . I 've also tried not to include email notification and still errors

**Comment by WilsonReddy** [comment]
@shak3800 can you comment line no. 809 and 838 in ProvisionHelperFunctions.cs in service and publish service? this should solve the problem.

File: ProvisionHelperFunctions.cs

\tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter.ProviderService\HelperClasses\ProvisionHelperFunctions.cs


Line 809 
// keys.Add(ServiceConstantStrings.StampedPropertyMatterCenterUserEmails);

Line 838
// propertyList.Add(ServiceConstantStrings.StampedPropertyMatterCenterUserEmails, Encoder.HtmlEncode(matterCenterUserEmails));

**Comment by WilsonReddy** [comment]
@shak3800  @smerentsov  latest code has fix for this issue. Get latest code and try.

**Comment by shak3800** [comment]
@WilsonReddy  I have tried your suggestion about commenting out Line 809 and 838 and still doesn't work. Is the fix this one or does it have additional fixed about my issue?

**Comment by WilsonReddy** [comment]
@shak3800 latest code has fixes. Take latest and try.

Sent from my Windows Phone

-----Original Message-----

**Comment by WilsonReddy** [comment]
Reopen if you still see this issue in latest code.
